import 'package:flutter/material.dart';

/// Color tokens for the «صالوني» design system, generated by hand from
/// `design/design-system/tokens.json` (color.tokens). Values MUST stay in
/// sync with that file — see `test/tokens_test.dart`, which parses the JSON
/// source of truth and asserts every value below matches it exactly.
///
/// The dark theme is the primary/default theme (ق38); light is derived.
@immutable
class SaloniColors extends ThemeExtension<SaloniColors> {
  const SaloniColors({
    required this.surface,
    required this.surfaceRaised,
    required this.surfaceElevated,
    required this.surfaceSunken,
    required this.line,
    required this.lineStrong,
    required this.ink,
    required this.inkMuted,
    required this.inkSubtle,
    required this.primary,
    required this.primaryStrong,
    required this.primarySoft,
    required this.onPrimary,
    required this.steel,
    required this.steelSoft,
    required this.success,
    required this.successSoft,
    required this.warning,
    required this.warningSoft,
    required this.danger,
    required this.dangerSoft,
    required this.onDanger,
    required this.focus,
    required this.overlay,
  });

  final Color surface;
  final Color surfaceRaised;
  final Color surfaceElevated;
  final Color surfaceSunken;
  final Color line;
  final Color lineStrong;
  final Color ink;
  final Color inkMuted;
  final Color inkSubtle;
  final Color primary;
  final Color primaryStrong;
  final Color primarySoft;
  final Color onPrimary;
  final Color steel;
  final Color steelSoft;
  final Color success;
  final Color successSoft;
  final Color warning;
  final Color warningSoft;
  final Color danger;
  final Color dangerSoft;
  final Color onDanger;
  final Color focus;
  final Color overlay;

  /// السلسلة الأولى في المخططات (مؤكد) — alias لـ [primary].
  Color get chart1 => primary;

  /// السلسلة الثانية (مقارنة) — alias لـ [steel].
  Color get chart2 => steel;

  /// السلسلة الثالثة (معلّق) — alias لـ [warning].
  Color get chart3 => warning;

  static const SaloniColors dark = SaloniColors(
    surface: Color(0xFF0E1726),
    surfaceRaised: Color(0xFF16233A),
    surfaceElevated: Color(0xFF1B2B46),
    surfaceSunken: Color(0xFF0A111D),
    line: Color(0xFF23324B),
    lineStrong: Color(0xFF5A6F8F),
    ink: Color(0xFFEAF1F8),
    inkMuted: Color(0xFFA3B3C8),
    inkSubtle: Color(0xFF8797AD),
    primary: Color(0xFF8CC8E6),
    primaryStrong: Color(0xFFB3DCF0),
    primarySoft: Color(0xFF1D3350),
    onPrimary: Color(0xFF0B1A2A),
    steel: Color(0xFF7FD1C7),
    steelSoft: Color(0xFF173A3F),
    success: Color(0xFF7FD6A4),
    successSoft: Color(0xFF143325),
    warning: Color(0xFFF2C27A),
    warningSoft: Color(0xFF3A2D17),
    danger: Color(0xFFFF9AA8),
    dangerSoft: Color(0xFF3F1A24),
    onDanger: Color(0xFF2A0A12),
    focus: Color(0xFFB3DCF0),
    overlay: Color.fromRGBO(3, 7, 14, 0.66),
  );

  static const SaloniColors light = SaloniColors(
    surface: Color(0xFFF3F6FA),
    surfaceRaised: Color(0xFFFFFFFF),
    surfaceElevated: Color(0xFFFFFFFF),
    surfaceSunken: Color(0xFFE7EDF4),
    line: Color(0xFFD8E0EA),
    lineStrong: Color(0xFF74869F),
    ink: Color(0xFF0F1B2D),
    inkMuted: Color(0xFF4B5B72),
    inkSubtle: Color(0xFF5D6D84),
    primary: Color(0xFF1F5F86),
    primaryStrong: Color(0xFF174A69),
    primarySoft: Color(0xFFE0EDF6),
    onPrimary: Color(0xFFFFFFFF),
    steel: Color(0xFF1B6A63),
    steelSoft: Color(0xFFDCEFED),
    success: Color(0xFF1F7045),
    successSoft: Color(0xFFDFF1E6),
    warning: Color(0xFF855000),
    warningSoft: Color(0xFFFCEFD8),
    danger: Color(0xFFAD2439),
    dangerSoft: Color(0xFFFBE4E8),
    onDanger: Color(0xFFFFFFFF),
    focus: Color(0xFF1F5F86),
    overlay: Color.fromRGBO(15, 27, 45, 0.45),
  );

  @override
  SaloniColors copyWith({
    Color? surface,
    Color? surfaceRaised,
    Color? surfaceElevated,
    Color? surfaceSunken,
    Color? line,
    Color? lineStrong,
    Color? ink,
    Color? inkMuted,
    Color? inkSubtle,
    Color? primary,
    Color? primaryStrong,
    Color? primarySoft,
    Color? onPrimary,
    Color? steel,
    Color? steelSoft,
    Color? success,
    Color? successSoft,
    Color? warning,
    Color? warningSoft,
    Color? danger,
    Color? dangerSoft,
    Color? onDanger,
    Color? focus,
    Color? overlay,
  }) {
    return SaloniColors(
      surface: surface ?? this.surface,
      surfaceRaised: surfaceRaised ?? this.surfaceRaised,
      surfaceElevated: surfaceElevated ?? this.surfaceElevated,
      surfaceSunken: surfaceSunken ?? this.surfaceSunken,
      line: line ?? this.line,
      lineStrong: lineStrong ?? this.lineStrong,
      ink: ink ?? this.ink,
      inkMuted: inkMuted ?? this.inkMuted,
      inkSubtle: inkSubtle ?? this.inkSubtle,
      primary: primary ?? this.primary,
      primaryStrong: primaryStrong ?? this.primaryStrong,
      primarySoft: primarySoft ?? this.primarySoft,
      onPrimary: onPrimary ?? this.onPrimary,
      steel: steel ?? this.steel,
      steelSoft: steelSoft ?? this.steelSoft,
      success: success ?? this.success,
      successSoft: successSoft ?? this.successSoft,
      warning: warning ?? this.warning,
      warningSoft: warningSoft ?? this.warningSoft,
      danger: danger ?? this.danger,
      dangerSoft: dangerSoft ?? this.dangerSoft,
      onDanger: onDanger ?? this.onDanger,
      focus: focus ?? this.focus,
      overlay: overlay ?? this.overlay,
    );
  }

  @override
  SaloniColors lerp(ThemeExtension<SaloniColors>? other, double t) {
    if (other is! SaloniColors) return this;
    Color l(Color a, Color b) => Color.lerp(a, b, t)!;
    return SaloniColors(
      surface: l(surface, other.surface),
      surfaceRaised: l(surfaceRaised, other.surfaceRaised),
      surfaceElevated: l(surfaceElevated, other.surfaceElevated),
      surfaceSunken: l(surfaceSunken, other.surfaceSunken),
      line: l(line, other.line),
      lineStrong: l(lineStrong, other.lineStrong),
      ink: l(ink, other.ink),
      inkMuted: l(inkMuted, other.inkMuted),
      inkSubtle: l(inkSubtle, other.inkSubtle),
      primary: l(primary, other.primary),
      primaryStrong: l(primaryStrong, other.primaryStrong),
      primarySoft: l(primarySoft, other.primarySoft),
      onPrimary: l(onPrimary, other.onPrimary),
      steel: l(steel, other.steel),
      steelSoft: l(steelSoft, other.steelSoft),
      success: l(success, other.success),
      successSoft: l(successSoft, other.successSoft),
      warning: l(warning, other.warning),
      warningSoft: l(warningSoft, other.warningSoft),
      danger: l(danger, other.danger),
      dangerSoft: l(dangerSoft, other.dangerSoft),
      onDanger: l(onDanger, other.onDanger),
      focus: l(focus, other.focus),
      overlay: l(overlay, other.overlay),
    );
  }
}
