#!/usr/bin/env bash
# Saloni — trial installer for a fresh Ubuntu or Debian VPS. Safe to run again (idempotent).
#
#   sudo bash deploy/install.sh [BRANCH] [--domain api.example.com]
#
# - Installs Docker (official get.docker.com script) if missing.
# - Run from inside a copy of the repository (git clone, or an uploaded + extracted archive), it uses
#   that copy as is. Run on its own (e.g. `curl -fsSL …/install.sh | sudo bash`), it clones the
#   repository into /opt/saloni (or $SALONI_DIR), or fast-forwards that clone if it already exists.
# - Creates deploy/.env with strong random secrets ONCE (existing values are never overwritten).
# - Domain: --domain / $SALONI_DOMAIN, else the one already in deploy/.env, else <ip-with-dashes>.sslip.io.
# - Opens 80/443 in ufw if ufw is active, builds, starts, waits for health, prints the API address.
set -euo pipefail

REPO_URL="${SALONI_REPO:-https://github.com/abdkamal/barber.git}"
BRANCH="claude/ecstatic-wozniak-fn1302"
DOMAIN_ARG="${SALONI_DOMAIN:-}"
ASSUME_YES="${SALONI_ASSUME_YES:-0}"

while [ $# -gt 0 ]; do
  case "$1" in
    --domain) DOMAIN_ARG="${2:-}"; shift 2 ;;
    --domain=*) DOMAIN_ARG="${1#*=}"; shift ;;
    --yes|-y) ASSUME_YES=1; shift ;;
    -h|--help) echo "usage: sudo bash deploy/install.sh [BRANCH] [--domain api.example.com]"; exit 0 ;;
    -*) echo "خيار غير معروف: $1" >&2; exit 1 ;;
    *) BRANCH="$1"; shift ;;
  esac
done

fail() { printf '\033[1;31m✘ %s\033[0m\n' "$*" >&2; exit 1; }

# ---- 0. Basic checks -------------------------------------------------------------------------
[ "$(uname -s)" = "Linux" ] || fail "هذا المثبّت يعمل على خادم Linux فقط (Ubuntu 22.04/24.04 أو Debian 12/13)."
[ "$(id -u)" -eq 0 ] || fail "شغّل المثبّت بصلاحية الجذر: sudo bash deploy/install.sh"

apt_install() {
  command -v apt-get >/dev/null 2>&1 || fail "لم أجد apt-get. استخدم Ubuntu 22.04/24.04 أو Debian 12/13، أو ثبّت يدويًا: $*"
  DEBIAN_FRONTEND=noninteractive apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "$@" >/dev/null
}
command -v curl >/dev/null 2>&1 || apt_install curl ca-certificates

# ---- 1. Locate (or fetch) the application ------------------------------------------------------
SELF="${BASH_SOURCE[0]:-}"
FOUND=""
if [ -n "$SELF" ] && [ -f "$SELF" ]; then
  CANDIDATE="$(cd "$(dirname "$SELF")/.." && pwd)"
  if [ -f "$CANDIDATE/server/package.json" ] && [ -f "$CANDIDATE/deploy/docker-compose.yml" ]; then FOUND="$CANDIDATE"; fi
fi
if [ -z "$FOUND" ]; then
  TARGET="${SALONI_DIR:-/opt/saloni}"
  if [ -d "$TARGET/.git" ]; then
    command -v git >/dev/null 2>&1 || apt_install git
    echo "==> تحديث النسخة الموجودة في $TARGET (الفرع $BRANCH)"
    git -C "$TARGET" fetch origin "$BRANCH"
    git -C "$TARGET" checkout -q "$BRANCH" 2>/dev/null || git -C "$TARGET" checkout -q -b "$BRANCH" "origin/$BRANCH"
    git -C "$TARGET" merge --ff-only -q "origin/$BRANCH"
  elif [ -f "$TARGET/server/package.json" ]; then
    echo "==> استخدام النسخة المرفوعة في $TARGET"
  else
    command -v git >/dev/null 2>&1 || apt_install git
    echo "==> تنزيل المشروع إلى $TARGET"
    echo "    (إن طُلب Username/Password: اسمك في GitHub، ثم «رمز وصول» Personal Access Token بدل كلمة المرور)"
    git clone --branch "$BRANCH" "$REPO_URL" "$TARGET"
  fi
  export SALONI_ASSUME_YES="$ASSUME_YES"
  if [ -n "$DOMAIN_ARG" ]; then
    exec bash "$TARGET/deploy/install.sh" "$BRANCH" --domain "$DOMAIN_ARG"
  fi
  exec bash "$TARGET/deploy/install.sh" "$BRANCH"
fi

# From here on we run from inside the application copy.
# shellcheck source=deploy/_common.sh
. "$FOUND/deploy/_common.sh"

say "التثبيت من: $APP_DIR"

# ---- 2. Docker -----------------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  say "تثبيت Docker (السكربت الرسمي get.docker.com)…"
  curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker >/dev/null 2>&1 || true
docker info >/dev/null 2>&1 || die "Docker مثبّت لكنه لا يعمل. جرّب: sudo systemctl restart docker"
docker compose version >/dev/null 2>&1 || apt_install docker-compose-plugin
ok "Docker جاهز: $(docker --version)"

# ---- 3. Secrets + settings (deploy/.env: created once, values never overwritten) ------------------
gen_secret() { head -c 48 /dev/urandom | base64 -w0 | tr '+/' '-_' | tr -d '='; }
ensure_var() { # KEY VALUE → append only if KEY is not set yet
  grep -q "^$1=" "$ENV_FILE" 2>/dev/null || printf '%s=%s\n' "$1" "$2" >>"$ENV_FILE"
}
set_var() { # KEY VALUE → set/replace (only for the domain, and only when the user passes it)
  if grep -q "^$1=" "$ENV_FILE"; then sed -i "s|^$1=.*|$1=$2|" "$ENV_FILE"; else printf '%s=%s\n' "$1" "$2" >>"$ENV_FILE"; fi
}

umask 077
if [ ! -f "$ENV_FILE" ]; then
  say "إنشاء أسرار جديدة في deploy/.env"
  {
    echo "# Saloni trial deployment — generated by install.sh on $(date -u +%F)."
    echo "# KEEP SECRET and do NOT delete: the database password and token secrets protect existing data and sessions."
  } >"$ENV_FILE"
fi
ensure_var PG_PASSWORD "$(gen_secret)"
ensure_var JWT_ACCESS_SECRET "$(gen_secret)"
ensure_var JWT_REFRESH_SECRET "$(gen_secret)"
ensure_var RESET_CODE_PEPPER "$(gen_secret)"
chmod 600 "$ENV_FILE"

detect_ip() {
  local ip url
  for url in https://api.ipify.org https://ifconfig.me/ip https://icanhazip.com; do
    ip="$(curl -4 -fsS --max-time 6 "$url" 2>/dev/null | tr -d '[:space:]' || true)"
    if [[ "$ip" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]]; then echo "$ip"; return 0; fi
  done
  return 1
}
PUBLIC_IP="$(detect_ip || true)"

if [ -n "$DOMAIN_ARG" ]; then
  set_var SALONI_DOMAIN "$DOMAIN_ARG"
elif [ -z "$(env_get SALONI_DOMAIN)" ]; then
  [ -n "$PUBLIC_IP" ] || die "تعذّر اكتشاف عنوان IP العام. أعد التشغيل مع نطاقك: sudo bash $DEPLOY_DIR/install.sh --domain api.example.com"
  set_var SALONI_DOMAIN "${PUBLIC_IP//./-}.sslip.io"
fi
DOMAIN="$(env_get SALONI_DOMAIN)"
ok "النطاق: $DOMAIN${PUBLIC_IP:+  (IP الخادم: $PUBLIC_IP)}"

# ---- 4. Firewall (only if ufw is active) -------------------------------------------------------
if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q "Status: active"; then
  ufw allow 80/tcp >/dev/null && ufw allow 443/tcp >/dev/null && ufw allow 443/udp >/dev/null
  ok "فُتح المنفذان 80 و443 في الجدار الناري ufw"
fi

# ---- 4b. Another proxy already owns port 80/443? → run behind it (edge mode) --------------------
# e.g. a Caddy container of another project on this VPS. Saloni's own Caddy is then not started;
# the API joins that proxy's Docker network as "saloni-api" and the proxy gets one extra site block.
OWN_CADDY="$(docker ps -q --filter label=com.docker.compose.project=saloni --filter label=com.docker.compose.service=caddy)"
EDGE_C="$(env_get SALONI_EDGE_CONTAINER)"
if [ -z "$EDGE_C" ] && [ -z "$OWN_CADDY" ]; then
  EDGE_C="$(docker ps --filter publish=80 --format '{{.Names}}' | head -n 1)"
  if [ -z "$EDGE_C" ] && command -v ss >/dev/null 2>&1 && ss -ltnH '( sport = :80 )' | grep -q .; then
    die "المنفذ 80 مشغول ببرنامج خارج Docker ($(ss -ltnpH '( sport = :80 )' | grep -o 'users:(("[^"]*' | head -n1 | cut -d'"' -f2)). أرسل هذه الرسالة للمطوّر."
  fi
fi
if [ -n "$EDGE_C" ]; then
  docker inspect "$EDGE_C" >/dev/null 2>&1 || die "الوكيل $EDGE_C المسجّل في deploy/.env غير موجود."
  EDGE_IMAGE="$(docker inspect --format '{{.Config.Image}}' "$EDGE_C")"
  case "$EDGE_IMAGE" in *caddy*) ;; *) die "المنفذ 80 يستخدمه $EDGE_C ($EDGE_IMAGE) وليس Caddy. أرسل هذه الرسالة للمطوّر ليجهّز الربط معه." ;; esac
  EDGE_NET="$(docker inspect --format '{{range $k, $v := .NetworkSettings.Networks}}{{$k}}{{"\n"}}{{end}}' "$EDGE_C" | grep -vxE 'bridge|host|none' | head -n 1 || true)"
  [ -n "$EDGE_NET" ] || die "الوكيل $EDGE_C على شبكة Docker الافتراضية فقط؛ لا يمكن الربط تلقائيًا. أرسل هذه الرسالة للمطوّر."
  set_var SALONI_EDGE_CONTAINER "$EDGE_C"
  set_var SALONI_EDGE_NETWORK "$EDGE_NET"
  ok "يوجد وكيل يملك المنفذين 80/443: $EDGE_C — سيعمل صالوني خلفه (شبكة $EDGE_NET) دون المساس بمواقعك"
  docker rm -f saloni-caddy-1 >/dev/null 2>&1 || true
fi

# ---- 5. Build + start --------------------------------------------------------------------------
say "بناء السيرفر (3–10 دقائق في المرة الأولى)…"
dc build server
say "تشغيل الخدمات…"
dc up -d --remove-orphans

say "بانتظار جاهزية السيرفر (تجهيز قاعدة البيانات)…"
if ! wait_server_healthy 300; then
  dc ps
  dc logs --tail 60 server
  die "السيرفر لم يصبح جاهزًا. انظر السجل أعلاه."
fi
ok "السيرفر يعمل داخليًا"

# ---- 5b. Edge mode: add Saloni's site block to the existing Caddy (backed up, validated, reversible)
edge_block() {
  cat <<BLOCK
# saloni-begin (added by /opt/saloni/deploy/install.sh — Saloni API; remove this block to detach)
$DOMAIN {
	encode gzip
	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		X-Content-Type-Options "nosniff"
		Referrer-Policy "no-referrer"
		-Server
	}
	request_body {
		max_size 6MB
	}
	reverse_proxy saloni-api:3000 {
		header_up X-Forwarded-For {remote_host}
	}
}
# saloni-end
BLOCK
}
if [ -n "$(env_get SALONI_EDGE_NETWORK)" ]; then
  EDGE_C="$(env_get SALONI_EDGE_CONTAINER)"
  edge_block >"$DEPLOY_DIR/edge-site.caddy"
  # Host file behind /etc/caddy/Caddyfile in that container (file mount, or the /etc/caddy directory).
  CF_IN="/etc/caddy/Caddyfile"
  CF_HOST="$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/etc/caddy/Caddyfile"}}{{.Source}}{{end}}{{end}}' "$EDGE_C")"
  if [ -z "$CF_HOST" ]; then
    D="$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/etc/caddy"}}{{.Source}}{{end}}{{end}}' "$EDGE_C")"
    [ -n "$D" ] && CF_HOST="$D/Caddyfile"
  fi
  manual_edge() {
    warn "أضف الكتلة الموجودة في $DEPLOY_DIR/edge-site.caddy إلى ملف Caddyfile الخاص بـ $EDGE_C ثم أعد تحميله:"
    warn "  docker exec $EDGE_C caddy reload --config $CF_IN --adapter caddyfile"
  }
  if [ -z "$CF_HOST" ] || [ ! -f "$CF_HOST" ]; then
    manual_edge
  elif grep -q '^# saloni-begin' "$CF_HOST"; then
    ok "كتلة صالوني موجودة مسبقًا في $CF_HOST"
  else
    say "سأضيف موقع صالوني ($DOMAIN) إلى إعدادات $EDGE_C"
    echo "    الملف: $CF_HOST — تؤخذ نسخة احتياطية منه، ويُفحص قبل التطبيق، ويُعاد كما كان إن فشل الفحص."
    echo "    مواقعك الحالية لا تتغير."
    REPLY=""
    if [ "$ASSUME_YES" = 1 ]; then REPLY=y
    elif [ -r /dev/tty ]; then read -r -p "    موافق؟ [y/N] " REPLY </dev/tty || true
    fi
    if [[ "$REPLY" =~ ^[Yy] ]]; then
      BK="$CF_HOST.bak-saloni-$(date +%Y%m%d%H%M%S)"
      cp -p "$CF_HOST" "$BK"
      { echo; edge_block; } >>"$CF_HOST"   # append in place: keeps the inode the container has mounted
      if docker exec "$EDGE_C" caddy validate --config "$CF_IN" --adapter caddyfile >/dev/null 2>&1 \
         && docker exec "$EDGE_C" caddy reload --config "$CF_IN" --adapter caddyfile >/dev/null 2>&1; then
        ok "أُضيف موقع صالوني إلى $EDGE_C (النسخة الاحتياطية: $BK)"
      else
        cat "$BK" >"$CF_HOST"
        docker exec "$EDGE_C" caddy reload --config "$CF_IN" --adapter caddyfile >/dev/null 2>&1 || true
        warn "فشل فحص الإعدادات الجديدة فأُعيد الملف كما كان."
        manual_edge
      fi
    else
      manual_edge
    fi
  fi
fi

say "فحص العنوان العام https://$DOMAIN …"
PUBLIC_OK=0
if wait_public_health "$DOMAIN"; then
  PUBLIC_OK=1
  ok "كل شيء يعمل!"
else
  warn "السيرفر يعمل لكن العنوان العام لم يستجب بعد. الأغلب أن المنفذين 80 و443 مغلقان في لوحة مزوّد الخادم"
  warn "(Firewall / Security group)، أو أن النطاق لا يشير إلى IP هذا الخادم. افتحهما وانتظر دقيقة ثم جرّب الرابط أدناه."
  if [ -n "$(env_get SALONI_EDGE_CONTAINER)" ]; then
    warn "سجل الوكيل: docker logs --tail 50 $(env_get SALONI_EDGE_CONTAINER)"
  else
    warn "سجل Caddy: sudo docker compose -f $DEPLOY_DIR/docker-compose.yml logs --tail 50 caddy"
  fi
fi

cat <<MSG

──────────────────────────────────────────────────────────────
  عنوان السيرفر (يُدخل في التطبيقين):  https://$DOMAIN
  فحص الصحة:   https://$DOMAIN/v1/health   ← يجب أن يظهر {"status":"ok"}
  صالونات بانتظار التفعيل:   sudo bash $DEPLOY_DIR/vendor.sh pending
  تفعيل صالون:              sudo bash $DEPLOY_DIR/vendor.sh activate <رمز الصالون>
  نسخة احتياطية:            sudo bash $DEPLOY_DIR/backup.sh
──────────────────────────────────────────────────────────────
MSG
[ "$PUBLIC_OK" = 1 ] || exit 2
